### ISSUE TITLE
"SyntaxError: Unexpected token :"  only in JSON (YAML works fine)

### ISSUE THREAD

**Issue by vikas027** [meetfinch/decking#90]
Hello,

I am trying out similar configurations in JSON and YAML files, but JSON one throws below error. I am referencing <a href="http://linux4you.tk/decking-create-docker-cluster-simple/" title="Title">this</a> article.

```bash
# cat decking.json
"containers": {
  "nginx1": "vikas027/nginx-ubuntu",
  "nginx2": "vikas027/nginx-ubuntu"
},
"clusters": {
  "main": ["nginx1", "nginx2"]
}
#
# decking status
SyntaxError: Unexpected token :
    at Object.parse (native)
    at Decking.loadConfig (/usr/lib/node_modules/decking/lib/decking.js:116:19)
    at Decking.execute (/usr/lib/node_modules/decking/lib/decking.js:89:24)
    at Object._onImmediate (/usr/lib/node_modules/decking/bin/decking:25:20)
    at processImmediate [as _immediateCallback] (timers.js:354:15)
#
```

However, YAML works just fine.
```bash
# cat decking.yaml
containers:
   nginx1:
     image: "vikas027/nginx-ubuntu"
   nginx2:
     image: "vikas027/nginx-ubuntu"
clusters:
   main:
     - "nginx1"
     - "nginx2"
# decking status
Defaulting to cluster 'main'
nginx1  ...
nginx2  ...
nginx1  does not exist
nginx2  ...
nginx1  does not exist
nginx2  does not exist
#
```
This is not super urgent, but I would like to know whether it is a bug or I am missing something.

Regards,
Vikas

**Comment by makeusabrew** [comment]
Hi @vikas027,

If that really is the contents of `decking.json` then yes, it's a simple JSON parse error: JSON always needs to start with an array or an object. Yours starts with a string. Simply wrap it in { }:
```
{
  "containers": {
    "nginx1": "vikas027/nginx-ubuntu",
    "nginx2": "vikas027/nginx-ubuntu"
  },
  "clusters": {
    "main": ["nginx1", "nginx2"]
  }
}
```

**Comment by vikas027** [comment]
Oh, my bad!
Thanks makeusabrew, this worked fine.
